services:
  app-duckdb:
    container_name: stac-fastapi-duckdb
    image: stac-utils/stac-fastapi-duckdb
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8084
      - RELOAD=true
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
      - STAC_FILE_PATH=/app/stac_collections
      - BACKEND=duckdb
      - PARQUET_URLS_JSON=${PARQUET_URLS_JSON}
    ports:
      - "8085:8084"
    volumes:
      - ./stac_collections:/app/stac_collections
      - ./stac_fastapi:/app/stac_fastapi
      - ./tests:/app/tests
    command:
      bash -c "python -m stac_fastapi.duckdb.app"